### ISSUE TITLE
WCC <> JSX Enhancements Tracking

### ISSUE THREAD

**Issue by thescientist13** [thescientist13/todo-app#2]
## Type of Change
- [x] New Feature Request
- [ ] Documentation
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
Coming out of #1 , there were few outstanding issues from the JSX migration that need to come from WCC.

## Details
1. [ ] `preventDefault()` on the form because using Enter to add a Todo refreshes the page - https://github.com/ProjectEvergreen/wcc/issues/89
1. [ ] Figure out how to enable attributes as variables so the checkbox actually checks, when checked - https://github.com/ProjectEvergreen/wcc/issues/89
1. [ ] Automatic observability - https://github.com/ProjectEvergreen/wcc/issues/87
1. [ ] Have WCC auto-call render onConnectedCallback?
    ```jsx
    export default class Footer extends HTMLElement {
      // TODO would be nice for WCC to auto render somehow?
      connectedCallback() {
        this.render();
      }
    
      render() {
        return (
          <footer>
            <a href="https://projectevergreen.github.io">Project Evergreen</a>
          </footer>
        );
      }
    }
    ```
